name: Back Bob Application CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - feat/github-actions-configuration

jobs:
  build_Back:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Maven
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build & Test
        working-directory: ./back
        run: mvn clean install

      - name: Artefact Coverage Back
        # if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage jacoco
          path: ./back/target/site/jacoco/

  sonar_Quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

      - name: SonarCloud Scan
        working-directory: ./back
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_BACK }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=adrienpiombini_p10-back -Dsonar.qualitygate.wait=true

  docker_actions:
    needs: [build_Back, sonar_Quality]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push on Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./back
          push: true
          tags: adrienpiombini/p10_bob_application_backend:latest
