name: GitHub Actions ðŸš€
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build with Maven
        run: mvn -B clean package
        working-directory: ${{ github.workspace }}/back

      - name: Test with JaCoCo
        run: mvn test jacoco:report
        working-directory: ${{ github.workspace }}/back

      - name: Archive JaCoCo reports
        uses: actions/upload-artifact@v2
        with:
          name: jacoco-reports
          path: target/site/jacoco/

        # COVERAGE RAPPORTS FRONT ðŸš€

      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.2'

      - name: Install angular-CLI
        run: npm install -g @angular/cli
        
      - name: Install dependenties
        run: npm install
        working-directory: ${{ github.workspace }}/front

      - name: Add dependenties to project
        run: ng add @angular/material
        working-directory: ${{ github.workspace }}/front
        
      - name: Run tests and generate coverage
        run: ng test --browsers=ChromeHeadless --code-coverage
        working-directory: ${{ github.workspace }}/front
        continue-on-error: true

      - name: Archive test and coverage reports
        uses: actions/upload-artifact@v2
        with:
          name: test-and-coverage-reports
          path: coverage/
        if: success() 
